export enum ExitOrientation {
    ChainonFourthFloor = 'chainon-fourth-floor',
    ChainonThirdFloor = 'chainon-third-floor',
    ChainonMYM = 'chainon-mym',
    ChainonMSM = 'chainon-msm',
    ChainonUTPE = 'chainon-utpe',
    HousingOrientation = 'housing-orientation',
    ReturnHome = 'return-home',
    ReturnToTheStreet = 'return-to-the-street',
    RPA = 'rpa',
    Hospital = 'hospital',
    DetoxCenter = 'detox-center',
    Death = 'death',
    Other = 'other',
}